Fix rigidbody mocap parsing
USC-ACTLab/libmotioncapture pull request #11
Opened 2021-04-21 15:42 UTC by jaredpaquet4ufl

I believe optitrack.cpp was simplified from https://github.com/whoenig/NatNetSDKCrossplatform/blob/master/src/PacketClient.cpp this request resolves an incorrect simplification of  line 661 through line 670

This resolves:
#6 
https://github.com/USC-ACTLab/crazyswarm/issues/364
possibly others

Tested on:
Ubuntu 18.04
Motive 2.2.0
NatNetVersion: 14.140.50.0
ServerVersion: 3.1.0.0

2021-04-25 18:34 UTC, whoenig commented
Good catch, but I don't think your fix is correct in all cases. In https://github.com/whoenig/NatNetSDKCrossplatform/blob/master/src/PacketClient.cpp#L661-L670, there is a variable being read `nMarkers`, which is of type int (i.e., 32 bits). ptr itself is of type char, i.e., 8 bits. Thus, dereferencing `ptr` might not lead to the correct result if more than 255 markers are visible. It would be better to rely on `memcpy`, similar to the original code in PacketClient.cpp.

2021-04-26 14:27 UTC, jaredpaquet4ufl commented
Thanks for the feedback. I have updated the code with your recommendations.

2021-04-27 01:46 UTC, whoenig commented on src/optitrack.cpp
> +            ptr += 12;
I'd suggest to remove this inner for loop and just add "ptr += nMarkers * 12;".

2021-04-27 01:47 UTC, whoenig requested changes
Please change the for-loop to a calculation instead.

2021-04-27 02:12 UTC, jaredpaquet4ufl commented
Completed requested changes

2021-04-27 18:00 UTC, merged

2021-04-27 18:01 UTC, whoenig commented
Perfect - thank you very much!